version : '3'
services:
    web2:
      build: .
      ports:
        - "8080:8080"
      links:
        - "mongo"
    mongo:
        image: 'mongo:latest'
        ports: 
          - '27117:27117'
        command: "mongod --port 27117"
